### PR TITLE
add missing parameters diskcache and pdfa to create Fpdi object

### LINKED ISSUE #9: Error when updating to latest Version 2.104.1
When updating to the latest version (in my case 2.102.0 to 2.104.1) the update aborts and the website is offline (error 500)

```
Package operations: 0 installs, 9 updates, 0 removals  
- Updating composer/ca-bundle (1.2.2 => 1.2.3): Loading from cache  
- Updating eluceo/ical (0.15.0 => 0.15.1): Loading from cache  
- Updating symfony/polyfill-mbstring (v1.11.0 => v1.12.0): Loading from cache  
- Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0): Loading from cache  
- Updating php-http/message (1.7.2 => 1.8.0): Loading from cache  
- Updating symfony/polyfill-php72 (v1.11.0 => v1.12.0): Loading from cache  
- Updating symfony/polyfill-intl-idn (v1.11.0 => v1.12.0): Loading from cache  
- Updating symfony/polyfill-iconv (v1.11.0 => v1.12.0): Loading from cache  
- Updating heimrichhannot/contao-utils-bundle (2.102.0 => 2.104.1): Loading from cache

Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Generating optimized autoload filesocramius/package-versions: Generating version class...ocramius/package-versions: ...done generating version classcontao/manager-plugin: 
Generating plugin class...contao/manager-plugin: ...done generating plugin class> 

Contao\ManagerBundle\Composer\ScriptHandler::initializeApplicationIn DefinitionErrorExceptionPass.php line 54:                                                                                 

Cannot autowire service "HeimrichHannot\UtilsBundle\File\FolderUtil": argument "$symlinksCommand" of method "__construct()" references class "Contao\CoreBundle\Command\SymlinksCommand" but no such service exists. You should maybe alias this class to the existing "contao.command.symlinks" service.
                                                                                   
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exceptionIn ScriptHandler.php line 89:  
An error occurred while executing the "contao:install-web-dir" command:        

In DefinitionErrorExceptionPass.php line 54:  Cannot autowire service "HeimrichHannot\UtilsBundle\File\FolderUtil": argument "$symlinksCommand" of method "__construct()" references class "Contao    \CoreBundle\Command\SymlinksCommand" but no such service exists. You should maybe alias this class to the existing "contao.command.symlinks" service. 

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...# Process terminated with exit code 1# Result: General error---### The background task has stopped unexpectedly ###
```

**Error:**

> In DefinitionErrorExceptionPass.php line 54:  Cannot autowire service "HeimrichHannot\UtilsBundle\File\FolderUtil": argument "$symlinksCommand" of method "__construct()" references class "Contao    \CoreBundle\Command\SymlinksCommand" but no such service exists. You should maybe alias this class to the existing "contao.command.symlinks" service. 

Afterwards Contao Manager requires a repair which won´t work. You have to restore the previous composer.json and repair with previous extension versions afterwards. So updating is not possible at the moment.

Frank

### LINKED ISSUE #11: Version 2.104.2: PHP Parse error:  syntax error, unexpected ')' in src/Pdf/FPDIWriter.php on line 154
```
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
PHP Parse error:  syntax error, unexpected ')' in myproject/vendor/heimrichhannot/contao-utils-bundle/src/Pdf/FPDIWriter.php on line 154
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred while executing the "contao:install-web-dir" command: PHP Parse error:  syntax error, unexpected ')' in myproject/vendor/heimrichhannot/contao-utils-bundle/src/Pdf/FPDIWriter.php on line 154
```

### PR DESCRIPTION
**Pull request by homberger**
Fixes #11

### CODE REVIEW

**Comment by Defcon0** [comment]
What error is being thrown and in which use case? I used the class already without issues.

**Comment by homberger** [comment]
>What error is being thrown and in which use case? I used the class already without issues.
The linked issue of my pull request was a different issue. I created issue #11 

This was a regular `composer update`.

**Comment by koertho** [comment]
The two parameters added in this pull request are not necessarily needed, as they are the default value from the tcpdf constructor. The error is the trailing comma in the constructor parameters, which isn't supported until PHP 7.4.
So I would prefer to just remove the trailing comma.

**Comment by homberger** [comment]
> The two parameters added in this pull request are not necessarily needed, as they are the default value from the tcpdf constructor. The error is the trailing comma in the constructor parameters, which isn't supported until PHP 7.4.
> So I would prefer to just remove the trailing comma.

Oh, I see! Thank you! :)

**Pull request closed without merging**
